spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      group-id: rpc
    producer:
      bootstrap-servers: localhost:9092


kafka:
  topic:
    rpc: rpc.request
    rpc-response: rpc.response